name: loquacious
description: An ORM inspired by Laravel Eloquent
version: 0.0.1
homepage: https://github.com/giusepetroso/loquacious.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.12 

flutter: null
